version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/git/deploy
    overwrite: yes
permissions: 
  - object: /home/ubuntu/git/deploy
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1500 
      runas: root