name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Source Code.
        uses: actions/checkout@v2
      - name: Check Node -V
        run: node -v
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Zip create
        run: zip -qq -r ./test-build.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./test-build.zip s3://test-mybucket-doyeon/test-build.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name test-reactApp-code-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name test-reactApp-deploy-group
          --s3-location bucket=test-mybucket-doyeon,key=test-build.zip,bundleType=zip