name: Deploy
on:
  push:
    branches:
      - master

env: 
  S3_BUCKET_NAME: test-mybucket-doyeon
  CODE_DEPLOY_APPLICATION_NAME: test-reactApp-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: test-reactApp-deploy-group


jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Source Code.
        uses: actions/checkout@v2
      - name: Check Node -V
        run: node -v
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Zip create
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://test-mybucket-doyeon/$GITHUB_SHA.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }}
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }}
          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip